---
- name: Ensure that work_dir exists
  file:
    dest: "{{ work_dir }}/archives"
    state: directory

- name: Copy archives to the build server
  copy:
    dest: "{{ work_dir }}/archives/"
    src: "{{ work_dir }}/archives/"

# Unpack Configs for each app server
- include_tasks: unarchive_configs.yml
  with_items:
    - "{{ groups['appservers'] }}"

# TODO: We should cycle through the unpacked configurations and do a
# sanity check

# Set up the project for OpenShift
- include_tasks: openshift_setup.yml

# Find all of the consolidated apps
- name: Go find the unpacked configs
  command: "ls {{ work_dir }}/consolidated/"
  register: ls

# Sanity check the Deployments
- include_tasks: sanity_check.yml
  with_items:
    - "{{ ls.stdout_lines }}"

# Migrate the Deployments
- include_tasks: migrate_deployment.yml
  with_items:
    - "{{ ls.stdout_lines }}"

# Loop through all of the application servers found and build and deploy them.
- include_tasks: build_deploy.yml
  with_items:
    - "{{ ls.stdout_lines }}"

